#!/bin/bash
brew install aspell
brew install the_silver_searcher
brew install --HEAD universal-ctags/universal-ctags/universal-ctags
brew install fd

curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz -o /tmp/nvim.tar.gz
tar -xzf /tmp/nvim.tar.gz -C ~/
rm /tmp/nvim.tar.gz
ln -sf ~/nvim-osx64/bin/nvim /usr/local/bin/nvim

ln -sf $PWD/config/init.vim ~/.config/nvim/init.vim
ln -sf $PWD/config/config ~/.config/nvim

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim --headless +PlugInstall +UpdateRemotePlugins +qa

ln -sf $PWD/.pylintrc ~/.pylintrc
ln -sf $PWD/pycodestyle ~/.config/pycodestyle

ln -sf $PWD/aspell/spelling /usr/local/bin/spelling
ln -sf $PWD/aspell/.aspell.en.prepl ~/.aspell.en.prepl
ln -sf $PWD/aspell/.aspell.en.pws ~/.aspell.en.pws
